package ui;
 
public class Admin extends javax.swing.JPanel {
 
    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
 
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>                        
 
 
    // Variables declaration - do not modify                     
    // End of variables declaration                   
 
    // ---------- เพิ่มเข้ามา: ไว้รันดูหน้านี้เดี่ยวๆ เร็วๆ ผ่าน VS Code ----------
    // ตอนนี้ panel ยังว่างเปล่า (ขนาด 970x600 ให้ตรงกับ Login/Dashboard) เพราะยังไม่ได้ใส่ component
    // เข้าไปใน initComponents() เปิดมาดูก่อนได้ว่าหน้าต่างขึ้นจริงไหม แล้วค่อยเพิ่ม component ทีหลัง
    // ตอนใช้งานจริงในโปรเจกต์ ไม่ต้องเรียก main() นี้ — เอา Admin ไปใส่ใน JFrame หลักของแอปแทน
    public static void main(String[] args) {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ignored) {
        }
        javax.swing.SwingUtilities.invokeLater(() -> {
            javax.swing.JFrame frame = new javax.swing.JFrame("Course Registration - Admin");
            frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
            frame.getContentPane().add(new Admin());
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
            frame.toFront();
        });
    }
}
